function add3dx(figure1,labs)

%
% Usage: add3dx(figh);
%		 add3dx(figh,labs)
%
% Silly litte function for adding x,y,z, labels to a 3-D figure. I wrote it
% because the standard Matlab placement is hard to control. Standard is
% x_1, x_2, x_3, but you can specify another with labs, e.g.,
%
% labs = {'x','y','z'}
%

if nargin < 2 || ~iscell(labs) || length(labs)<3
	labs = {'x_1', 'x_2', 'x_3'};
end

annotation(...
  figure1,'textbox',...
  'Position',[0.75 0.05 0.05714 0.05],...
  'LineStyle','none',...
  'FitHeightToText','off',...
  'FontSize',12,...
  'HorizontalAlignment','center',...
  'String',labs{1});
 
annotation(...
  figure1,'textbox',...
  'Position',[0.1682 0.08714 0.05714 0.05],...
  'LineStyle','none',...
  'FitHeightToText','off',...
  'FontSize',12,...
  'HorizontalAlignment','center',...
  'String',labs{2});
 
annotation(...
  figure1,'textbox',...
  'Position',[0.04179 0.8243 0.05714 0.05],...
  'LineStyle','none',...
  'FitHeightToText','off',...
  'FontSize',12,...
  'HorizontalAlignment','center',...
  'String',labs{3});